# Generated by Django 6.0 on 2026-05-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_producto_disponible"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cerveza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                ("grados", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="producto",
            name="disponible",
            field=models.BooleanField(db_default=False),
        ),
    ]
